### ISSUE TITLE
ModpidyAPI().library.get_images

### ISSUE THREAD

**Issue by lucblender** [AsbjornOlling/mopidyapi#1]
There is an error with the get_image of the Library Controller.  (Python 3.6.3)
The following code:

> m = MopidyAPI()
> track = m.playback.get_current_track()
> m.library.get_images([track.uri])

Get this error:

> 
> 2019-05-20 19:35:49.845 | ERROR    | mopidyapi.httpclient:rpc_call:84 - An error has been caught in function 'rpc_call', process 'MainProcess' (18154), thread 'MainThread' (1996312576):
> Traceback (most recent call last):
> 
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.6/site-packages/mopidyapi/controllers/library.py", line 159, in get_images
>     return self.client.rpc_call('core.library.get_images', *args, **kwargs)
>            |    |      |                                    |       -> {}
>            |    |      |                                    -> (['spotify:track:1mgWnqeUOurHJIyorDtuqF'],)
>            |    |      -> <bound method MopidyAPI.rpc_call of <mopidyapi.httpclient.MopidyAPI object at 0x76c6e4f0>>
>            |    -> <mopidyapi.httpclient.MopidyAPI object at 0x76c6e4f0>
>            -> <mopidyapi.controllers.library.LibraryController object at 0x76c6e5f0>
> > File "/usr/local/lib/python3.6/site-packages/mopidyapi/httpclient.py", line 84, in rpc_call
>     return deserialize_mopidy(r['result'])
>            |                  -> {'jsonrpc': '2.0', 'id': 0, 'result': {'spotify:track:1mgWnqeUOurHJIyorDtuqF': [{'width': 640, '__model__': 'Image', 'uri': 'htt...
>            -> <function deserialize_mopidy at 0x76003738>
>   File "/usr/local/lib/python3.6/site-packages/mopidyapi/parsedata.py", line 44, in deserialize_mopidy
>     raise ValueError(f"Uncaught type: {type(data)}")
>           -> <class 'ValueError'>
> 
> ValueError: Uncaught type: <class 'dict'>

**Comment by lucblender** [comment]
commit 94805fd from the 04/06/2019 have fixed it! Modification still not available through pip installation though but working with the source works perfectly

**Comment by lucblender** [comment]
Version 0.6.4 available on pip fix the problem!

Thanks for your work
